[package]
name = "rocket_auth"
version = "0.1.0"
authors = ["tvallotton@uc.cl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["sqlite-db", "postgres-db", "redis-session"]
sqlite-db = ["rusqlite"]
postgres-db = ["tokio-postgres"]
redis-session = ["redis"]
# mysql-db = [...]



[dependencies]
rand = "0.8.3"
rust-argon2 = "0.8.3"

lazy_static = "1.4.0"
regex = "1"
serde_json = "1.0.59"
chashmap = "2.2.2"

[dependencies.rocket]
version = "0.4.7"
features = ["private-cookies"]

[dependencies.serde]
version = "1.0.125"
features = ["derive"]

[dependencies.tokio-postgres]
version = "0.7.0"
optional = true

[dependencies.rusqlite]
version = "0.24.1"
optional = true

[dependencies.redis]
version = "0.20.0"
features = ["aio", "tokio-comp"]
optional = true
